CREATE TABLE heroes (
    id INT(13) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    hero VARCHAR(30),
    pattribute VARCHAR(13),
    available BOOLEAN NOT NULL DEFAULT 1,
    banned BOOLEAN NOT NULL DEFAULT 0,
    initialban BOOLEAN NOT NULL DEFAULT 0
);

/* Strength Heroes */
INSERT INTO heroes (hero, pattribute) VALUES ('Earthshaker', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Sven', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Tiny', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Kunkka', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Beastmaster', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Dragon Knight', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Clockwerk', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Omniknight', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Huskar', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Alchemist', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Brewmaster', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Treant Protector', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Io', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Centaur Warruner', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Timbersaw', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Bristleback', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Tusk', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Elder Titan', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Legion Commander', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Earth Spirit', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Phoenix', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Axe', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Pudge', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Sand King', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Slardar', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Tidehunter', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Wraith King', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Lifestealer', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Night Stalker', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Doom', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Spirit Breaker', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Lycan', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Chaos Knight', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Undying', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Magnus', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Abaddon', 'strength');
INSERT INTO heroes (hero, pattribute) VALUES ('Underlord', 'strength');
/* Agility Heroes */
INSERT INTO heroes (hero, pattribute) VALUES ('Anti-Mage', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Drow Ranger', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Juggernaut', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Mirana', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Morphling', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Phantom Lancer', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Vengeful Spirit', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Riki', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Sniper', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Templar Assassin', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Luna', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Bounty Hunter', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Ursa', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Gyrocopter', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Lone Druid', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Naga Siren', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Troll Warlord', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Ember Spirit', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Monkey King', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Bloodseeker', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Shadow Fiend', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Razor', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Venomancer', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Faceless Void', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Phantom Assassin', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Viper', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Clinkz', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Broodmother', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Weaver', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Spectre', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Meepo', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Nyx Assassin', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Slark', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Medusa', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Terrorblade', 'agility');
INSERT INTO heroes (hero, pattribute) VALUES ('Arc Warden', 'agility');
/* Intelligence Heroes */
INSERT INTO heroes (hero, pattribute) VALUES ('Crystal Maiden', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Puck', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Storm Spirit', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Windranger', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Zeus', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Lina', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Shadow Shaman', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Tinker', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Nature\'s Prophet', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Enchantress', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Jakiro', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Chen', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Silencer', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Ogre Magi', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Rubick', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Disruptor', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Keeper of the Light', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Skywrath Mage', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Oracle', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Techies', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Bane', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Lich', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Lion', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Witch Doctor', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Enigma', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Necrophos', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Warlock', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Queen of Pain', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Death Prophet', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Pugna', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Dazzle', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Leshrac', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Dark Seer', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Batrider', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Ancient Apparition', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Invoker', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Outworld Devourer', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Shadow Demon', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Visage', 'intelligence');
INSERT INTO heroes (hero, pattribute) VALUES ('Winter Wyvern', 'intelligence');
